export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const REGISTER_LOGIN_SIGNOUT_USER = "REGISTER_LOGIN_SIGNOUT_USER";

export const SAVE_USER_DATA = "SAVE_USER_DATA";

export const GET_POSTS = 'GET_POSTS'

export const CREATE_POST = "CREATE_POST";

export const MAIN_LOADER = "MAIN_LOADER";

export const FIREBASE_LOADER = "FIREBASE_LOADER";
